[meta title:"Lorenze Attractor" description:"A quick post on the Lorenz attractor" /]

[IdyllLogo /]

[Header
  title:"Lorenz Attractor"
  author:"Matthew Conlen"
  authorLink:"https://twitter.com/mathisonian" /]


The [link text:"Lorenz Attractor" href:"http://mathworld.wolfram.com/LorenzAttractor.html" /]
is a set of chaotic solutions to the Lorenz system, defined by three coupled non-linear
equations:

[var name:"a" value:10 /]
[var name:"b" value:28 /]
[var name:"c" value:`2.66` /]

[equation display:`true` a:a domain:`{a: [-20, 20]}` interval:`{a: 0.5}` ]
\frac{\delta x}{\delta t} = a (y - x)
[/equation]

[equation display:`true` b:b domain:`{b: [-30, 30]}` interval:`{b: 0.5}`]
\frac{\delta y}{\delta t} = x (b - z) - y
[/equation]

[equation display:`true` c:c domain:`{c: [-0, 20]}` interval:`{c: 0.05}`]
\frac{\delta z}{\delta t} = xy - c z
[/equation]

[var name:"focused" value:`false` /]
[fixed]
[Lorenz a:a b:b c:c focused:focused /]
[small]Enable mouse control: [boolean value:focused /][/small]
[/fixed]

On the right, you can see an implementation of the Lorenz attractor in WebGL using [link href:"http://regl.party/" text:"regl" /].

Note that the equations above are dynamic. You can click on the constants `a`, `b`, or `c` and change their values to
radically change the appearance of the attractor.

The code that I used to create this was modified from [link text:"this gist" href:"https://gist.github.com/aemkei/1320178" /], which contains a
basic implementation in 140 bytes. I modified it to use a WebGL particle system, and dynamically respond to updates of the constants. I also
added in a [a href:"https://github.com/rreusser/regl-camera"]controllable camera[/a], so that you can click and drag on the rendered output to change your viewpoint
(although the scrolling is a little wonky - sorry about that!).

Here's the code I ended up with to make this Idyll component:

[gist gist:"c2b342f0ce3a900673c8091bc2f74c3c" file:"lorenz.js" /]

Read more about Idyll at [link href:"https://idyll-lang.github.io/" text:"https://idyll-lang.github.io/" /],
or [link href:"https://github.com/mathisonian/lorenz" text:"check out the source for this example" /].


[analytics google:"UA-93774348-1" tag:"lorenz" /]